name: Lint and build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Verify linting
        run: yarn lint
      - name: Build
        run: yarn build
